contracts/main/stablecoin-core/LiquidationEngine.sol, contracts/main/stablecoin-core/adapters/FarmableTokenAdapter/AnkrCollateralAdapter.sol
1)liq.engine now emits events when batchLiq's iteration fails 2)LogCertsInflow&Outflow added
=> events added

contracts/main/price-oracles/DexPriceOracle.sol, contracts/main/stablecoin-core/BookKeeper.sol, contracts/main/stablecoin-core/LiquidationEngine.sol, contracts/main/stablecoin-core/PriceOracle.sol, contracts/main/stablecoin-core/SystemDebtEngine.sol, contracts/main/stablecoin-core/adapters/FarmableTokenAdapter/AnkrCollateralAdapter.sol, contracts/main/stablecoin-core/adapters/StablecoinAdapter.sol, contracts/main/stablecoin-core/adapters/TokenAdapter.sol
2.2.5 It is not possible to cage already caged contracts in ShowStopper - fixed
=> allow to cage already caged contracts, small fixes

contracts/main/interfaces/IAnkrColAdapter.sol, contracts/main/stablecoin-core/adapters/FarmableTokenAdapter/AnkrCollateralAdapter.sol, scripts/deployment/1_collateral-pool-config/config/collateral-pool-config.js
forgot to include interface change which is needed to make the compilation go thru.
=> ankrColAdapter_ueslessAmountConversion_interfaceadjustment

contracts/main/stablecoin-core/LiquidationEngine.sol
- Check array length for all the arguments to validate inputs.
- Added more catch conditions to capture failed liquidation.
=> BatchLiquidation Audit Fixes

contracts/main/flash-mint/FlashMintModule.sol, contracts/main/interfaces/IPausable.sol, contracts/main/stablecoin-core/AdminControls.sol, contracts/main/stablecoin-core/BookKeeper.sol, contracts/main/stablecoin-core/LiquidationEngine.sol, contracts/main/stablecoin-core/PriceOracle.sol, contracts/main/stablecoin-core/StabilityFeeCollector.sol, contracts/main/stablecoin-core/StableSwapModule.sol, contracts/main/stablecoin-core/SystemDebtEngine.sol, contracts/main/stablecoin-core/adapters/StablecoinAdapter.sol, scripts/migrations/deployment/1_deploy.js, scripts/migrations/deployment/2_deployProxies.js, scripts/migrations/deployment/3_initialize.js, scripts/migrations/deployment/4_add-roles.js, scripts/migrations/test/configuration/2_add-collateral-pools.js, scripts/tests/integration/AdminControls.test.js, scripts/tests/unit/stablecoin-core/AdminControls.test.js
Introduce AdminControls contract responsible for pausing and unpausing protocol.
=> Pause protocol flow

contracts/main/managers/PositionManager.sol, contracts/main/stablecoin-core/BookKeeper.sol, contracts/main/stablecoin-core/LiquidationEngine.sol, contracts/main/stablecoin-core/PriceOracle.sol, contracts/main/stablecoin-core/ShowStopper.sol, contracts/main/stablecoin-core/liquidation-strategies/FixedSpreadLiquidationStrategy.sol
2.3.4 "Sanity check" call will not revert for some types of the contracts - fixed. Added "require" checks and some setters
=> put sanity checks inside the require checks, add more setters

contracts/main/stablecoin-core/liquidation-strategies/FixedSpreadLiquidationStrategy.sol
2.3.14 Missing validations of stablecoinAdapter in FixedSpreadLiquidationStrategy- fixed, sanity check added
=> add stablecoinAdapter sanity check

contracts/main/interfaces/IStablecoin.sol, contracts/main/stablecoin-core/FathomStablecoin.sol
Added IERC20 Interface inheritance
=> 2.4.22 Missing IERC20 interface in FathomStablecoin

contracts/main/stablecoin-core/PriceOracle.sol
ISetPrice Added as missing inheritance
=> 2.4.23 Missing interface inheritance in PriceOracle

contracts/main/stablecoin-core/liquidation-strategies/FixedSpreadLiquidationStrategy.sol
Removed WAD from fixed spread liquidation strategy
=> 2.4.12 WAD is never used in FixedSpreadLiquidationStrategy

contracts/main/stablecoin-core/config/AccessControlConfig.sol
Changed some constants to immutable in AccessControlConfig
=> 2.4.34 constant variables can be changed in AccessControlConfig

contracts/main/stablecoin-core/LiquidationEngine.sol
=> 2.4.37 Unsuitable modifier for setPriceOracle setter in LiquidationEngine

contracts/main/stablecoin-core/PriceOracle.sol
Unnecessary Import and Contract removed
=> 2.4.41 Unnecessary inheritance from ReentrancyGuardUpgradeable in PriceOracle

contracts/main/stablecoin-core/FathomStablecoin.sol
=> 2.4.42 nonces variable is not used in FathomStablecoin

contracts/main/interfaces/IStableSwapModule.sol, contracts/main/interfaces/IStableSwapModuleWrapper.sol, contracts/main/stablecoin-core/StableSwapModule.sol, contracts/main/stablecoin-core/StableSwapModuleWrapper.sol, contracts/tests/mocks/ERC20MintableStableSwap.sol, scripts/migrations/deployment/3_initialize.js, scripts/migrations/test/pre-deployment/1_deploy-mocks.js, scripts/tests/integration/StableSwapModule.test.js, scripts/tests/integration/StableSwapModuleWrapper.test.js, scripts/tests/unit/stablecoin-core/StableSwapModule.test.js
Worked on:
- Logical error of _amount not being scaled
- Making overrides in stableswap so that stableswap wrapper fetches from it
- Getter function in stableswap wrapper
- Tests
Remaining:
- Fix unit tests
=> Updates to wrapper as per feedback

scripts/tests/integration/StableSwapModule.test.js, scripts/tests/unit/stablecoin-core/StableSwapModule.test.js, scripts/tests/unit/stablecoin-core/StableSwapModuleWrapper.test.js
Removed few unit tests that were failing as it wont work on Unit testing, so shifted few of it to integration testing
Added few more unit tests
=> Fixing Unit Tests

contracts/main/interfaces/IStableSwapModuleWrapper.sol, contracts/main/stablecoin-core/StableSwapModuleWrapper.sol, scripts/tests/integration/StableSwapModuleWrapper.test.js, scripts/tests/unit/stablecoin-core/StableSwapModuleWrapper.test.js
Added account as param
Removed divide by 2, in getter as it was not needed
=> Added Account as param, plus fixed one logical issue

contracts/main/stablecoin-core/config/CollateralPoolConfig.sol, scripts/tests/unit/config/CollateralPoolConfig.test.js
=> add debtCeiling and debtFloor validation

contracts/main/managers/PositionManager.sol, scripts/tests/unit/managers/PositionManager.test.js
=> add ok validation

contracts/main/flash-mint/FlashMintModule.sol, contracts/main/interfaces/ICollateralPoolConfig.sol, contracts/main/interfaces/IGenericTokenAdapter.sol, contracts/main/interfaces/IPriceOracle.sol, contracts/main/interfaces/IStableSwapModule.sol, contracts/main/managers/PositionManager.sol, contracts/main/price-oracles/lib/FathomSwapLibrary.sol, contracts/main/proxy-actions/FathomStablecoinProxyActions.sol, contracts/main/proxy-wallet/ProxyActionsStorage.sol, contracts/main/stablecoin-core/BookKeeper.sol, contracts/main/stablecoin-core/LiquidationEngine.sol, contracts/main/stablecoin-core/PriceOracle.sol, contracts/main/stablecoin-core/ShowStopper.sol, contracts/main/stablecoin-core/StabilityFeeCollector.sol, contracts/main/stablecoin-core/StableSwapModule.sol, contracts/main/stablecoin-core/StableSwapModuleWrapper.sol, contracts/main/stablecoin-core/SystemDebtEngine.sol, contracts/main/stablecoin-core/adapters/CollateralTokenAdapter/CollateralTokenAdapter.sol, contracts/main/stablecoin-core/adapters/StablecoinAdapter.sol, contracts/main/stablecoin-core/config/CollateralPoolConfig.sol, contracts/main/stablecoin-core/liquidation-strategies/FixedSpreadLiquidationStrategy.sol, contracts/tests/mocks/MockCollateralTokenAdapter.sol, contracts/tests/mocks/TokenAdapter.sol
=> remove redundant imports

contracts/main/proxy-wallet/ProxyActionsStorage.sol, contracts/main/proxy-wallet/ProxyWalletRegistry.sol, contracts/main/stablecoin-core/LiquidationEngine.sol, contracts/main/stablecoin-core/PriceOracle.sol, contracts/main/stablecoin-core/ShowStopper.sol, contracts/main/stablecoin-core/StabilityFeeCollector.sol, contracts/main/stablecoin-core/StableSwapModule.sol, contracts/main/stablecoin-core/StableSwapModuleWrapper.sol, contracts/main/stablecoin-core/SystemDebtEngine.sol, contracts/main/stablecoin-core/adapters/StablecoinAdapter.sol, contracts/main/stablecoin-core/liquidation-strategies/FixedSpreadLiquidationStrategy.sol, contracts/tests/mocks/TokenAdapter.sol
Remove redundant use of the IBookKeeper interface casting
=> remove unnecessary IBookKeeper interface casting

contracts/main/flash-mint/FlashMintModule.sol, contracts/main/flash-mint/base/FlashLoanReceiverBase.sol, contracts/main/managers/PositionManager.sol, contracts/main/proxy-actions/FathomStablecoinProxyActions.sol, contracts/main/stablecoin-core/BookKeeper.sol, contracts/main/stablecoin-core/FathomStablecoin.sol, contracts/main/stablecoin-core/LiquidationEngine.sol, contracts/main/stablecoin-core/PriceOracle.sol, contracts/main/stablecoin-core/ShowStopper.sol, contracts/main/stablecoin-core/StabilityFeeCollector.sol, contracts/main/stablecoin-core/SystemDebtEngine.sol, contracts/main/stablecoin-core/adapters/CollateralTokenAdapter/CollateralTokenAdapter.sol, contracts/main/stablecoin-core/adapters/StablecoinAdapter.sol, contracts/main/stablecoin-core/config/CollateralPoolConfig.sol, contracts/main/stablecoin-core/liquidation-strategies/FixedSpreadLiquidationStrategy.sol
=> Removing safe math

contracts/main/flash-mint/FlashMintModule.sol, contracts/main/price-feeders/DelayFathomOraclePriceFeed.sol, contracts/main/proxy-wallet/ProxyActionsStorage.sol, contracts/main/proxy-wallet/ProxyWalletRegistry.sol, contracts/main/stablecoin-core/ShowStopper.sol, contracts/main/stablecoin-core/StableSwapModule.sol, scripts/tests/unit/stablecoin-core/StableSwapModule.test.js
fix for infos: 8, 18, 19, 29, 30, 32, 47, 50
=> Pausable cleaning

contracts/main/proxy-actions/FathomStablecoinProxyActions.sol, contracts/main/stablecoin-core/FathomStablecoin.sol, contracts/main/stablecoin-core/LiquidationEngine.sol, contracts/main/stablecoin-core/ShowStopper.sol, contracts/main/stablecoin-core/Vault.sol, contracts/main/stablecoin-core/adapters/CollateralTokenAdapter/CollateralTokenAdapter.sol, scripts/migrations/add-collateral/deployment/3_initialize.js, scripts/migrations/deployment/3_initialize.js, scripts/tests/unit/stablecoin-core/FathomStablecoin.test.js, scripts/tests/unit/stablecoin-core/LiquidationEngine.test.js
info fixes: 23, 25, 26, 36, 39, 40, 53
=> More infos cleaning

contracts/main/proxy-actions/FathomStablecoinProxyActions.sol, scripts/tests/helper/positions.js
=> collect stability fee on wipe token flow

contracts/main/flash-mint/FlashMintModule.sol, contracts/main/interfaces/IDelayPriceFeed.sol, contracts/main/interfaces/IFathomCentralizedOracle.sol, contracts/main/price-feeders/DelayPriceFeedBase.sol, contracts/main/price-oracles/FathomPriceOracle.sol, contracts/main/price-oracles/PluginPriceOracle.sol, contracts/main/proxy-wallet/ProxyWalletRegistry.sol, contracts/main/stablecoin-core/AdminControls.sol, contracts/main/stablecoin-core/BookKeeper.sol, contracts/main/stablecoin-core/LiquidationEngine.sol, contracts/main/stablecoin-core/PriceOracle.sol, contracts/main/stablecoin-core/StabilityFeeCollector.sol, contracts/main/stablecoin-core/StableSwapModule.sol, contracts/main/stablecoin-core/adapters/CollateralTokenAdapter/CollateralTokenAdapter.sol, contracts/main/stablecoin-core/config/CollateralPoolConfig.sol, contracts/main/stablecoin-core/liquidation-strategies/FixedSpreadLiquidationStrategy.sol, contracts/tests/mocks/MockCollateralTokenAdapter.sol, contracts/tests/mocks/ParanoidDexOraclePriceFeed.sol, scripts/tests/integration/CollateralTokenAdapter.test.js, scripts/tests/unit/price-feeds/CentralizedOraclePriceFeed.test.js
A list of commits.
FXD-72 '23 Dec 21 clean indexed event param changes
FXD-72 '23 Dec 21 clean comments on test script
FXD-72 '23 Dec 21 remove deprecated storage slots
FXD-72 '23 Dec 21 adding event to WL, setBookKeeper fns
FXD-72 '23 Dec 21 adding event to setAccessControlConfig fns
FXD-72 '23 Dec 21 adding comment to setDecentralizedStatesStatus fn
=> Dec 21 '23 last changes before audit.

contracts/main/stablecoin-core/StableSwapModuleWrapper.sol
LP's contribution ratio is calculated and multiplied by the available fee calculated based on checkpoint.
=> FXD-74 2023 29th Dec, fee calculation bug fix
