Into-the-Fathom/fathom-stablecoin-smart-contracts

contracts/main/stablecoin-core/adapters/FarmableTokenAdapter/AnkrCollateralAdapter.sol
2.1.2 certsToMoveRatio not calculated properly in AnkrCollateralAdapter
SEVERITY CRITICAL STATUS NEW
Description
In AnkrCollateralAdapter.sol#L334 the certsToMoveRatio variable is not calculated in the situation when _share >= stake[_source]. Since certsToMoveRatio is initialized before the if statement, it always equals 0, thus the certsMove variable will also always be 0 and that breaks the logic of calculation of calculatedNewRatio .
Recommendation
We recommend to calculate certsToMoveRatio in all cases.
=> iter1_2.1.2 fix

.gitignore, contracts/main/price-oracles/lib/FathomSwapLibrary.sol
Description
In the FathomSwapLibrary contract the getReserves function will return reserves for non- existent pair, which may lead to incorrect calculations of the price. If the factory address is incorrect, or the pair was not created yet, the staticcall call will not revert and the output variable data will be 0x and the success will be always true . In this case inline assembly block mload(sub(fmp, 0x40)) will work incorrectly and will return the other non-empty internal slot with value 704374636544 . This value will be used in the getPrice function and may lead to incorrect calculations of the price. The getPrice function will return incorrect price for the pair, which may lead to incorrect calculations of the price in the entire system.
Recommendation
We recommend to add a validation …
=> Dev ankr integration 2 2 4 fathom swap library validation of returned data

contracts/main/price-oracles/DexPriceOracle.sol
DexPriceOralce audit fixes:
2.2.6 Small denominator in DexPriceOracle - fixed by casting to the same decimals before price calculation
2.3.6 Incorrect price with equal tokens in DexPriceOracle - fixed by reverting the same tokens
=> DexPriceOralce audit fixes

contracts/main/proxy-actions/FathomStablecoinProxyActions.sol, contracts/main/stablecoin-core/adapters/FarmableTokenAdapter/AnkrCollateralAdapter.sol
reasons for fix
we don't need to convert _amount to some other unit since already in ProxyActions contract, the _amount is msg.value(which is wei :10^18) that's why even when to18ConversionFactor was 1, everything worked fine. Therefore I removed needless conversion factors and decimals which comes from aXDCcAddress. This ankrColAdapter doesn't care about aXDCc when it deals with _share.
=> Dev ankr integration 2 1 6 useless amount conversion delete

contracts/main/stablecoin-core/ShowStopper.sol, scripts/migrations/deployment/4_add-roles.js, scripts/tests/integration/ShowStopper.test.js
2.1.2 finalizeCashPrice uses totalStablecoinIssued instead of poolStablecoinIssued to calculate price for specified collateralPoolId in ShowStopper - fixed. now we use poolStablecoinIssued for the calculations
=> Finalize price post-audit fix

contracts/main/stablecoin-core/PriceOracle.sol, scripts/tests/unit/stablecoin-core/PriceOracle.test.js
2.2.3 There are not enough checks in the setStableCoinReferencePrice function in PriceOracle - fixed. added validation to check if the new value is not zero and  match expected range
=> add validations to setStablecoinReferencePrice function, adjust tests

contracts/main/interfaces/IFathomOraclePriceFeed.sol, contracts/main/interfaces/IPriceFeed.sol, contracts/main/price-feeders/DelayFathomOraclePriceFeed.sol, contracts/main/stablecoin-core/config/CollateralPoolConfig.sol, contracts/tests/mocks/SimplePriceFeed.sol, scripts/migrations/deployment/3_initialize.js, scripts/tests/unit/config/CollateralPoolConfig.test.js, scripts/tests/unit/price-feeds/DelayFathomOraclePriceFeed.test.js
2.2.12 There are not enough checks in the setPriceFeed function in CollateralPoolConfig - fixed.
added check:
-zero address check
- added poolId to IPriceOrale and now we compare it to the collateralPoolId
- call isPriceOk to prevent unhealthy price feed setting
added peekPrice call
adjusted tests
=> setPriceFeed function update

contracts/main/stablecoin-core/StableSwapModule.sol, contracts/main/stablecoin-core/config/CollateralPoolConfig.sol, scripts/tests/unit/config/CollateralPoolConfig.test.js
2.2.13 There are not enough checks in the setLiquidationRatio function in CollateralPoolConfig - fixed.
added validations to check if liquidationRatio >= min and liquidationRatio =< max
=> add validations to setLiquidationRatio function

contracts/main/stablecoin-core/liquidation-strategies/FixedSpreadLiquidationStrategy.sol
2.2.11 Stablecoins from any _collateralReceiver address can be used to liquidate tokens in LiquidationEngine - fixed. now we use stablecoins from the liquidators address
=> now we will spend liquidator's stablecoin instead of recipient's to liquidate the position

contracts/main/managers/PositionManager.sol, scripts/tests/unit/managers/PositionManager.test.js
2.3.2 importPosition , exportPosition and movePosition move _debtShare instead of _lockedCollateral in PositionManager - fixed, now we use _lockedCollateral instead of _debtShare
=> fix issue with onMoveCollateral calls in position manager, adjust tests

contracts/main/stablecoin-core/BookKeeper.sol
Added sanity checks in Bookkeeper during initialization to check:
- non-contract address - also checks zero address
=> 2.3.36 Missing zero address validation in BookKeeper

contracts/main/stablecoin-core/BookKeeper.sol, scripts/tests/unit/stablecoin-core/BookKeeper.test.js
2.3.5 The settleSystemBadDebt, mintUnbackedStablecoin, and accrueStabilityFee methods do not operate with the poolStablecoinIssued variable in BookKeeper - fixed. 
Issued unbacked stablecoins shouldn't be considered pool-issued stablecoins, since they aren't bound to any pool (not backed by any collateral). Therefore, we don't need to calculate poolStablecoinIssued in settleSystemBadDebt, mintUnbackedStablecoin.
poolStablecoinIssued calculation was added to confiscate position and accrueStabilityFee because they deal with stablecoins bound to a particular pool.
=> update poolStablecoinIssued variable on confiscatePosition and accrueStabilityFee calls

contracts/main/proxy-wallet/FathomAuth.sol
2.3.6 Compromised authority may change owner of ProxyWallet - fixed. onlyOwner modifier added to setOwner function
=> make setOwner function accessible only by owner

contracts/main/stablecoin-core/StabilityFeeCollector.sol, contracts/main/stablecoin-core/config/CollateralPoolConfig.sol, scripts/tests/unit/config/CollateralPoolConfig.test.js, scripts/tests/unit/stablecoin-core/StabilityFeeCollector.test.js
2.3.9 Zero stabilityFee blocks the collect function in StabilityFeeCollector - fixed, now we don't allow zero stabilityFee.
=> don't allow zero stability fee rate

contracts/main/stablecoin-core/liquidation-strategies/FixedSpreadLiquidationStrategy.sol, scripts/tests/unit/liquidation-strategies/FixedSpreadLiquidationStrategy.test.js
Using hard-coded access role. did not create extra variable due to variables getting too many in a function
=> 2.4.38 Using a hard-coded access role instead of reference to _accessControlConfig in FixedSpreadLiquidationStrategy

contracts/main/stablecoin-core/BookKeeper.sol
onlyOwner modifier already checks it
=> 2.4.43 Unnecessary re-checking of the rights to execute a method in BookKeeper

contracts/main/stablecoin-core/adapters/CollateralTokenAdapter/CollateralTokenAdapter.sol
As per auditors:
require(_collateralValue > -2**255, "AnkrCollateralAdapter/tooSmallCollateralValue");
=> 2.4.48 The sign of the minimum value of type int256 can not be changed

contracts/main/stablecoin-core/LiquidationEngine.sol
There is a redundant modifier in batchLiquidate, whenNotPaused, as it calls this.liquidateForBatch, which has whenNotPaused modifier in it
=> 2.4.6 Redundant modifier in batchLiquidate in LiquidationEngine

contracts/main/price-oracles/DexPriceOracle.sol
The casting is not neccessary as in function signature the returns is actually uint256
=> 2.4.58 Unnecessary casting to uint64 in DexPriceOracle

contracts/main/interfaces/IStableSwapModuleWrapperRetriever.sol, contracts/main/stablecoin-core/StableSwapModule.sol, scripts/tests/integration/StableSwapModule.test.js, scripts/upgrades/0_062023/zeroedInEmergencyWithdraw-SSM-fix/upgrade-contracts-SSM.js, scripts/upgrades/0_062023/zeroedInEmergencyWithdraw-SSM-fix/zeroedValuesOnEmergencyWithdraw.md, scripts/upgrades/fix-zeroedOnEmergencyWithdraw/upgrade-contracts-SSM.js
Following was done:
- In emergencyWithdraw totalValueDeposited, totalTokenFeeBalance, totalFXDFeeBalance was zeroed
- Added a function udpateTotalValueDeposited() that updates totalValueDeposited to correct value
=> Several important variables are not zeroed in `emergencyWithdraw` in `StableSwapModule`
